pipeline {
    agent any

    environment {
        APP_URL     = "http://65.0.74.194:3000"
        IMAGE_NAME  = "shopease-selenium-tests"
        RESULTS_DIR = "${WORKSPACE}/test-results"
    }

    triggers {
        githubPush()
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh "docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ."
            }
        }

        stage('Run Selenium Tests') {
            steps {
                echo "Running Selenium tests..."

                sh """
                    rm -rf ${RESULTS_DIR}
                    mkdir -p ${RESULTS_DIR}

                    docker run --rm \
                        --name shopease-tests-${BUILD_NUMBER} \
                        -e BASE_URL=${APP_URL} \
                        -v ${RESULTS_DIR}:/app/test-results \
                        ${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }

        stage('Verify Test Report') {
            steps {
                echo "Checking generated test reports..."
                sh "ls -R ${RESULTS_DIR}"
            }
        }

        stage('Publish Results') {
            steps {
                junit testResults: 'test-results/results.xml', allowEmptyResults: false
            }
        }

        stage('Cleanup Docker Image') {
            steps {
                sh "docker rmi ${IMAGE_NAME}:${BUILD_NUMBER} || true"
            }
        }
    }

    post {
        always {
            script {

                def status = currentBuild.currentResult
                def color  = status == 'SUCCESS' ? '#16a34a' : '#dc2626'
                def emoji  = status == 'SUCCESS' ? '✅' : '❌'

                emailext(
                    subject: "${emoji} ShopEase Selenium Tests — ${status} [Build #${BUILD_NUMBER}]",
                    mimeType: 'text/html',
                    body: """
                        <div style="font-family:Arial;">
                            <h2 style="color:${color}">${emoji} Test Report</h2>

                            <p><b>Project:</b> ${env.JOB_NAME}</p>
                            <p><b>Build:</b> #${BUILD_NUMBER}</p>
                            <p><b>Status:</b> ${status}</p>
                            <p><b>App URL:</b> ${APP_URL}</p>

                            <hr>
                            <p>Generated by Jenkins CI/CD pipeline</p>
                        </div>
                    """,
                    recipientProviders: [
                        [$class: 'RequesterRecipientProvider'],
                        [$class: 'DevelopersRecipientProvider']
                    ]
                )
            }
        }
    }
}